apiVersion: v1
kind: ConfigMap
metadata:
  name: rhesis-worker-config
  labels:
    app.kubernetes.io/name: rhesis-worker
    app.kubernetes.io/instance: rhesis-worker
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/component: worker
data:
  LOG_LEVEL: "info"
  ENVIRONMENT: "production"
  BACKEND_API_URL: "http://rhesis-backend.payments.svc.cluster.local"
  worker-config.yaml: |
    worker:
      concurrency: 5
      retry:
        maxAttempts: 3
        initialBackoff: 5s
        maxBackoff: 60s
      monitoring:
        enabled: true
        metricsPort: 9090
      tasks:
        - name: data-processing
          queue: data-processing-queue
          handler: /app/handlers/data-processor.js
          timeout: 300s
        - name: notification
          queue: notification-queue
          handler: /app/handlers/notification.js
          timeout: 60s

