apiVersion: apps/v1
kind: Deployment
metadata:
  name: rhesis-worker
  labels:
    app.kubernetes.io/name: rhesis-worker
    app.kubernetes.io/instance: rhesis-worker
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/component: worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: rhesis-worker
      app.kubernetes.io/instance: rhesis-worker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rhesis-worker
        app.kubernetes.io/instance: rhesis-worker
    spec:
      serviceAccountName: rhesis-worker
      securityContext:
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
      containers:
        - name: rhesis-worker
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            runAsUser: 10001
            runAsGroup: 10001
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          image: "gcr.io/mutech2030/rhesis-worker:1.0.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 2
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
          env:
            - name: CONFIG_FILE
              value: "/config/worker-config.yaml"
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: rhesis-worker-config
                  key: LOG_LEVEL
            - name: QUEUE_URL
              valueFrom:
                secretKeyRef:
                  name: rhesis-worker-secret
                  key: QUEUE_URL
          volumeMounts:
            - name: config-volume
              mountPath: /config
              readOnly: true
            - name: tmp-volume
              mountPath: /tmp
      volumes:
        - name: config-volume
          configMap:
            name: rhesis-worker-config
        - name: tmp-volume
          emptyDir: {}
      nodeSelector:
        kubernetes.io/os: linux
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - rhesis-worker
                topologyKey: kubernetes.io/hostname
      tolerations: []

