apiVersion: v1
kind: Secret
metadata:
  name: rhesis-worker-secret
  labels:
    app.kubernetes.io/name: rhesis-worker
    app.kubernetes.io/instance: rhesis-worker
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/component: worker
type: Opaque
stringData:
  QUEUE_URL: "amqp://user:password@rabbitmq.messaging.svc.cluster.local:5672/vhost"
  API_KEY: "worker-api-key-for-backend-access"
  DATABASE_URL: "postgres://worker:password@postgres.database.svc.cluster.local:5432/rhesis"

