apiVersion: v1
kind: Service
metadata:
  name: guardduty
  namespace: guardduty
  labels:
    app.kubernetes.io/name: guardduty
    app.kubernetes.io/instance: guardduty
    cloud-provider: aws
    platform: eks
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: guardduty
    app.kubernetes.io/instance: guardduty
    app.kubernetes.io/component: controller
