apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../namespaces
  - services/rhesis-worker
  - services/rhesis-polyphemus
  - services/rhesis-frontend
  - services/rhesis-sdk
