apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-config
  namespace: istio
  labels:
    app.kubernetes.io/name: istio
    app.kubernetes.io/instance: istio
    cloud-provider: aws
    platform: eks
data:
  cloud-provider: "aws"
  platform: "eks"
  region: "us-west-2"
  cluster-name: "eks-cluster"
