apiVersion: v1
kind: Service
metadata:
  name: istio
  namespace: istio
  labels:
    app.kubernetes.io/name: istio
    app.kubernetes.io/instance: istio
    cloud-provider: aws
    platform: eks
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: istio
    app.kubernetes.io/instance: istio
    app.kubernetes.io/component: controller
