apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio
  namespace: istio
  labels:
    app.kubernetes.io/name: istio
    app.kubernetes.io/instance: istio
    cloud-provider: aws
    platform: eks
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::ACCOUNT_ID:role/istio-role"
automountServiceAccountToken: true
