apiVersion: v1
kind: ConfigMap
metadata:
  name: calico-config
  namespace: calico
  labels:
    app.kubernetes.io/name: calico
    app.kubernetes.io/instance: calico
    cloud-provider: aws
    platform: eks
data:
  cloud-provider: "aws"
  platform: "eks"
  region: "us-west-2"
  cluster-name: "eks-cluster"
