apiVersion: v1
kind: ServiceAccount
metadata:
  name: calico
  namespace: calico
  labels:
    app.kubernetes.io/name: calico
    app.kubernetes.io/instance: calico
    cloud-provider: aws
    platform: eks
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::ACCOUNT_ID:role/calico-role"
automountServiceAccountToken: true
