apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: datadog
  labels:
    app.kubernetes.io/name: datadog
    app.kubernetes.io/instance: datadog
    cloud-provider: aws
    platform: eks
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: datadog
subjects:
  - kind: ServiceAccount
    name: datadog
    namespace: datadog
