apiVersion: v1
kind: ConfigMap
metadata:
  name: datadog-config
  namespace: datadog
  labels:
    app.kubernetes.io/name: datadog
    app.kubernetes.io/instance: datadog
    cloud-provider: aws
    platform: eks
data:
  cloud-provider: "aws"
  platform: "eks"
  region: "us-west-2"
  cluster-name: "eks-cluster"
