apiVersion: apps/v1
kind: Deployment
metadata:
  name: datadog
  namespace: datadog
  labels:
    app.kubernetes.io/name: datadog
    app.kubernetes.io/instance: datadog
    app.kubernetes.io/component: controller
    cloud-provider: aws
    platform: eks
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: datadog
      app.kubernetes.io/instance: datadog
      app.kubernetes.io/component: controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: datadog
        app.kubernetes.io/instance: datadog
        app.kubernetes.io/component: controller
    spec:
      serviceAccountName: datadog
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
      containers:
        - name: datadog
          image: gcr.io/dummy/datadog:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 10001
            runAsGroup: 10001
          env:
            - name: CLOUD_PROVIDER
              value: "aws"
            - name: PLATFORM
              value: "eks"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
