apiVersion: v1
kind: ServiceAccount
metadata:
  name: datadog
  namespace: datadog
  labels:
    app.kubernetes.io/name: datadog
    app.kubernetes.io/instance: datadog
    cloud-provider: aws
    platform: eks
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::ACCOUNT_ID:role/datadog-role"
automountServiceAccountToken: true
