apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hpa
  labels:
    app.kubernetes.io/name: hpa
    app.kubernetes.io/instance: hpa
    cloud-provider: aws
    platform: eks
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hpa
subjects:
  - kind: ServiceAccount
    name: hpa
    namespace: hpa
