apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - configmap.yaml

commonAnnotations:
  description: "AWS EKS hpa base configuration"
  managed-by: kustomize
  cloud-provider: aws
  platform: eks
