apiVersion: v1
kind: ServiceAccount
metadata:
  name: hpa
  namespace: hpa
  labels:
    app.kubernetes.io/name: hpa
    app.kubernetes.io/instance: hpa
    cloud-provider: aws
    platform: eks
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::ACCOUNT_ID:role/hpa-role"
automountServiceAccountToken: true
