apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: datadog-secret
  namespace: datadog
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "datadog/api-key"
        objectType: "secretsmanager"
  secretObjects:
    - secretName: datadog-secret
      type: Opaque
      data:
        - key: api-key
          objectName: api-key
