apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: datadog
    repo: https://helm.datadoghq.com
    version: 3.63.2
    releaseName: datadog
    namespace: datadog
    valuesFile: values.yaml
