# components/datadog/values.yaml

datadog:
  apiKeyExistingSecret: datadog-secret  # Kubernetes secret with key `api-key`
  site: datadoghq.eu  # or datadoghq.com depending on your region

  logs:
    enabled: true
    containerCollectAll: true

  apm:
    enabled: true

  processAgent:
    enabled: true

agents:
  containers:
    agent:
      resources:
        limits:
          cpu: 200m
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 128Mi
    process:
      resources:
        limits:
          cpu: 150m
          memory: 128Mi
        requests:
          cpu: 75m
          memory: 64Mi
    trace:
      resources:
        limits:
          cpu: 150m
          memory: 128Mi
        requests:
          cpu: 75m
          memory: 64Mi
    logs:
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 50m
          memory: 64Mi

daemonset:
  useHostPort: false

clusterAgent:
  enabled: false  # unless needed

datadog:
  apiKeyExistingSecret: datadog-secret
