apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: payments-qa
resources:
  - ../../base
images:
  - name: gcr.io/mutech2030/rhesis-polyphemus
    newName: gcr.io/mutech2030/rhesis-polyphemus
    newTag: 1.0.0-qa
labels:
  - pairs:
      app: rhesis-polyphemus
      environment: qa
patches:
  - target:
      kind: Deployment
      name: rhesis-polyphemus
    path: patch-deployment.yaml
