- op: replace
  path: /spec/replicas
  value: 3
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: ENV
    value: stage
- op: replace
  path: /spec/template/spec/containers/0/resources/limits/cpu
  value: 400m
- op: replace
  path: /spec/template/spec/containers/0/resources/limits/memory
  value: 512Mi
- op: replace
  path: /spec/template/spec/containers/0/resources/requests/cpu
  value: 200m
- op: replace
  path: /spec/template/spec/containers/0/resources/requests/memory
  value: 256Mi

