- op: replace
  path: /spec/replicas
  value: 5
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: ENV
    value: production
- op: replace
  path: /spec/template/spec/containers/0/resources/limits/cpu
  value: 1000m
- op: replace
  path: /spec/template/spec/containers/0/resources/limits/memory
  value: 1024Mi
- op: replace
  path: /spec/template/spec/containers/0/resources/requests/cpu
  value: 500m
- op: replace
  path: /spec/template/spec/containers/0/resources/requests/memory
  value: 512Mi
- op: replace
  path: /spec/template/spec/affinity/podAntiAffinity/preferredDuringSchedulingIgnoredDuringExecution/0/weight
  value: 100
- op: add
  path: /spec/template/spec/topologySpreadConstraints
  value:
    - maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: rhesis-worker

