adminPassword: grafana123
service:
  type: LoadBalancer
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        url: http://loki.monitoring.svc.cluster.local:3100
        access: proxy
        isDefault: false
      - name: Tempo
        type: tempo
        url: http://tempo.monitoring.svc.cluster.local:3100
        access: proxy
        isDefault: false
      - name: Mimir
        type: prometheus
        url: http://mimir-query-frontend.monitoring.svc.cluster.local:8080
        access: proxy
        isDefault: true
