apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: lgtm
  labels:
    app.kubernetes.io/name: lgtm
    app.kubernetes.io/instance: lgtm
    cloud-provider: aws
    platform: eks
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: lgtm
subjects:
  - kind: ServiceAccount
    name: lgtm
    namespace: lgtm
