apiVersion: v1
kind: ConfigMap
metadata:
  name: lgtm-config
  namespace: lgtm
  labels:
    app.kubernetes.io/name: lgtm
    app.kubernetes.io/instance: lgtm
    cloud-provider: aws
    platform: eks
data:
  cloud-provider: "aws"
  platform: "eks"
  region: "us-west-2"
  cluster-name: "eks-cluster"
