apiVersion: v1
kind: Service
metadata:
  name: lgtm
  namespace: lgtm
  labels:
    app.kubernetes.io/name: lgtm
    app.kubernetes.io/instance: lgtm
    cloud-provider: aws
    platform: eks
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: lgtm
    app.kubernetes.io/instance: lgtm
    app.kubernetes.io/component: controller
