apiVersion: v1
kind: ServiceAccount
metadata:
  name: lgtm
  namespace: lgtm
  labels:
    app.kubernetes.io/name: lgtm
    app.kubernetes.io/instance: lgtm
    cloud-provider: aws
    platform: eks
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::ACCOUNT_ID:role/lgtm-role"
automountServiceAccountToken: true
