apiVersion: v1
kind: Secret
metadata:
  name: rhesis-polyphemus-secret
  labels:
    app.kubernetes.io/name: rhesis-polyphemus
    app.kubernetes.io/instance: rhesis-polyphemus
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/component: api
type: Opaque
stringData:
  API_KEY: "polyphemus-api-key-for-backend-access"
  DATABASE_URL: "postgres://polyphemus:password@postgres.database.svc.cluster.local:5432/rhesis"
  JWT_SECRET: "secure-jwt-secret-for-authentication"

