apiVersion: v1
kind: ServiceAccount
metadata:
  name: rhesis-polyphemus
  labels:
    app.kubernetes.io/name: rhesis-polyphemus
    app.kubernetes.io/instance: rhesis-polyphemus
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/component: api
automountServiceAccountToken: true

