apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudwatch-config
  namespace: cloudwatch
  labels:
    app.kubernetes.io/name: cloudwatch
    app.kubernetes.io/instance: cloudwatch
    cloud-provider: aws
    platform: eks
data:
  cloud-provider: "aws"
  platform: "eks"
  region: "us-west-2"
  cluster-name: "eks-cluster"
