apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudwatch
  namespace: cloudwatch
  labels:
    app.kubernetes.io/name: cloudwatch
    app.kubernetes.io/instance: cloudwatch
    cloud-provider: aws
    platform: eks
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::ACCOUNT_ID:role/cloudwatch-role"
automountServiceAccountToken: true
