apiVersion: v1
kind: Service
metadata:
  name: cloudwatch
  namespace: cloudwatch
  labels:
    app.kubernetes.io/name: cloudwatch
    app.kubernetes.io/instance: cloudwatch
    cloud-provider: aws
    platform: eks
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: cloudwatch
    app.kubernetes.io/instance: cloudwatch
    app.kubernetes.io/component: controller
