apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: quik-tls-secret
  namespace: payments
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "quik.com/tls"   # AWS Secrets Manager secret name or ARN
        objectType: "secretsmanager"
  secretObjects:
    - secretName: quik-tls
      type: kubernetes.io/tls
      data:
        - key: tls.crt
          objectName: tls.crt
        - key: tls.key
          objectName: tls.key
