apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - daemonset.yaml
  - serviceaccount.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - configmap.yaml
  - secret.yaml

commonAnnotations:
  description: "Azure Defender DaemonSet base configuration"
  managed-by: kustomize
