apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: payments
resources:
  - ../../base
components:
  - ../../../../components/debug
images:
  - name: gcr.io/mutech2030/rhesis-worker
    newName: gcr.io/mutech2030/rhesis-worker
    newTag: 1.0.0-dev
labels:
  - pairs:
      app: rhesis-worker
      environment: dev
patches:
  - target:
      kind: Deployment
      name: rhesis-worker
    path: patch-deployment.yaml

