apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../namespaces
  - services/rhesis-backend
  - services/rhesis-worker
  - services/rhesis-polyphemus
  - services/rhesis-frontend
  - services/rhesis-sdk
  - components/nginx-ingress
  - components/lgtm
  - components/defender
  - components/calico
  - components/datadog
  - components/monitor
  - components/istio
  - components/disk-csi
  - components/file-csi
  - components/secrets-store-csi
  - components/externaldns
  - components/argocd
  - components/github-actions-runner
  - components/keda
  - components/hpa

