apiVersion: v1
kind: Secret
metadata:
  name: datadog-secret
  namespace: datadog
  labels:
    app.kubernetes.io/name: datadog
    app.kubernetes.io/instance: datadog
type: Opaque
stringData:
  api-key: "your-datadog-api-key"
  app-key: "your-datadog-app-key"
