apiVersion: v1
kind: ServiceAccount
metadata:
  name: datadog-agent
  namespace: datadog
  labels:
    app.kubernetes.io/name: datadog
    app.kubernetes.io/instance: datadog
automountServiceAccountToken: true
