apiVersion: v1
kind: ServiceAccount
metadata:
  name: efs-csi
  namespace: efs-csi
  labels:
    app.kubernetes.io/name: efs-csi
    app.kubernetes.io/instance: efs-csi
    cloud-provider: aws
    platform: eks
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::ACCOUNT_ID:role/efs-csi-role"
automountServiceAccountToken: true
