apiVersion: v1
kind: Service
metadata:
  name: efs-csi
  namespace: efs-csi
  labels:
    app.kubernetes.io/name: efs-csi
    app.kubernetes.io/instance: efs-csi
    cloud-provider: aws
    platform: eks
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: efs-csi
    app.kubernetes.io/instance: efs-csi
    app.kubernetes.io/component: controller
