apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd
    app.kubernetes.io/instance: argocd
    cloud-provider: aws
    platform: eks
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::ACCOUNT_ID:role/argocd-role"
automountServiceAccountToken: true
