resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - secret.yaml

  
commonAnnotations:
  description: base-configuration
  managed-by: kustomize
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization