apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: quik-tls-secret
  namespace: default
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "certs/dev-service-c-tls"
        objectType: "secretsmanager"
  secretObjects:
    - secretName: quik-tls
      type: kubernetes.io/tls
      data:
        - key: tls.crt
          objectName: cert
        - key: tls.key
          objectName: key
