apiVersion: v1
kind: ServiceAccount
metadata:
  name: ebs-csi
  namespace: ebs-csi
  labels:
    app.kubernetes.io/name: ebs-csi
    app.kubernetes.io/instance: ebs-csi
    cloud-provider: aws
    platform: eks
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::ACCOUNT_ID:role/ebs-csi-role"
automountServiceAccountToken: true
