apiVersion: v1
kind: Secret
metadata:
  name: rhesis-frontend-secret
  labels:
    app.kubernetes.io/name: rhesis-frontend
    app.kubernetes.io/instance: rhesis-frontend
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/component: frontend
type: Opaque
stringData:
  ANALYTICS_KEY: "frontend-analytics-key"
  ERROR_REPORTING_KEY: "frontend-error-reporting-key"
  SESSION_SECRET: "secure-session-secret-for-frontend"
