apiVersion: v1
kind: ServiceAccount
metadata:
  name: rhesis-frontend
  labels:
    app.kubernetes.io/name: rhesis-frontend
    app.kubernetes.io/instance: rhesis-frontend
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/component: frontend
automountServiceAccountToken: true
