apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: payments

resources:
  - ../../base

components:
  - ../../../../components/debug

labels:
  - includeSelectors: true
    pairs:
      environment: dev

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: react-frontend
    path: patch-deployment.yaml
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: service-c-ingress
    path: patch-ingress.yaml



images:
  - name: react-frontend
    newName: node
    newTag: 18.17.1-alpine