apiVersion: v1
kind: Service
metadata:
  name: aws-audit-manager
  namespace: aws-audit-manager
  labels:
    app.kubernetes.io/name: aws-audit-manager
    app.kubernetes.io/instance: aws-audit-manager
    cloud-provider: aws
    platform: eks
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: aws-audit-manager
    app.kubernetes.io/instance: aws-audit-manager
    app.kubernetes.io/component: controller
