apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-audit-manager
  namespace: aws-audit-manager
  labels:
    app.kubernetes.io/name: aws-audit-manager
    app.kubernetes.io/instance: aws-audit-manager
    cloud-provider: aws
    platform: eks
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::ACCOUNT_ID:role/aws-audit-manager-role"
automountServiceAccountToken: true
