apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: externaldns
  labels:
    app.kubernetes.io/name: externaldns
    app.kubernetes.io/instance: externaldns
    cloud-provider: aws
    platform: eks
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: externaldns
subjects:
  - kind: ServiceAccount
    name: externaldns
    namespace: externaldns
