apiVersion: v1
kind: ConfigMap
metadata:
  name: externaldns-config
  namespace: externaldns
  labels:
    app.kubernetes.io/name: externaldns
    app.kubernetes.io/instance: externaldns
    cloud-provider: aws
    platform: eks
data:
  cloud-provider: "aws"
  platform: "eks"
  region: "us-west-2"
  cluster-name: "eks-cluster"
