apiVersion: v1
kind: Service
metadata:
  name: externaldns
  namespace: externaldns
  labels:
    app.kubernetes.io/name: externaldns
    app.kubernetes.io/instance: externaldns
    cloud-provider: aws
    platform: eks
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: externaldns
    app.kubernetes.io/instance: externaldns
    app.kubernetes.io/component: controller
