apiVersion: v1
kind: ServiceAccount
metadata:
  name: externaldns
  namespace: externaldns
  labels:
    app.kubernetes.io/name: externaldns
    app.kubernetes.io/instance: externaldns
    cloud-provider: aws
    platform: eks
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::ACCOUNT_ID:role/externaldns-role"
automountServiceAccountToken: true
