apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster1-services
spec:
  generators:
    - git:
        repoURL: https://github.com/MuTech2030/k8s-cluster-app-argocd-deployments.git
        revision: main
        directories:
          - path: apps/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/MuTech2030/k8s-cluster-app-argocd-deployments.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://192.168.64.3:6443
        namespace: payment
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
