apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secrets-manager-csi
  labels:
    app.kubernetes.io/name: secrets-manager-csi
    app.kubernetes.io/instance: secrets-manager-csi
    cloud-provider: aws
    platform: eks
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch"]
