apiVersion: v1
kind: Namespace
metadata:
  name: secrets-manager-csi
  labels:
    app.kubernetes.io/name: secrets-manager-csi
    app.kubernetes.io/instance: secrets-manager-csi
    cloud-provider: aws
    platform: eks
