apiVersion: v1
kind: ServiceAccount
metadata:
  name: secrets-manager-csi
  namespace: secrets-manager-csi
  labels:
    app.kubernetes.io/name: secrets-manager-csi
    app.kubernetes.io/instance: secrets-manager-csi
    cloud-provider: aws
    platform: eks
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::ACCOUNT_ID:role/secrets-manager-csi-role"
automountServiceAccountToken: true
