apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-ingress-config
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: nginx-ingress
    app.kubernetes.io/instance: nginx-ingress
    cloud-provider: aws
    platform: eks
data:
  cloud-provider: "aws"
  platform: "eks"
  region: "us-west-2"
  cluster-name: "eks-cluster"
