apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: argo-tls-secret
  namespace: argocd
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "argo.quik.internal/tls"
        objectType: "secretsmanager"
  secretObjects:
    - secretName: argo-tls
      type: kubernetes.io/tls
      data:
        - key: tls.crt
          objectName: tls.crt
        - key: tls.key
          objectName: tls.key
