# components/argocd/values.yaml

server:
  resources:
    limits:
      cpu: 250m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    type: LoadBalancer

repoServer:
  resources:
    limits:
      cpu: 250m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

applicationController:
  resources:
    limits:
      cpu: 300m
      memory: 384Mi
    requests:
      cpu: 150m
      memory: 256Mi

dex:
  enabled: false

redis:
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

server:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - argocd.internal.quik.com
    annotations:
      kubernetes.io/ingress.class: nginx
      external-dns.alpha.kubernetes.io/hostname: argocd.internal.quik.com
    tls:
      - hosts:
          - argocd.quik.internal
        secretName: argo-tls



  service:
    type: ClusterIP  # Change to ClusterIP since ingress will expose it
