apiVersion: v1
kind: ConfigMap
metadata:
  name: github-actions-runner-config
  namespace: github-actions-runner
  labels:
    app.kubernetes.io/name: github-actions-runner
    app.kubernetes.io/instance: github-actions-runner
    cloud-provider: aws
    platform: eks
data:
  cloud-provider: "aws"
  platform: "eks"
  region: "us-west-2"
  cluster-name: "eks-cluster"
