apiVersion: v1
kind: Service
metadata:
  name: github-actions-runner
  namespace: github-actions-runner
  labels:
    app.kubernetes.io/name: github-actions-runner
    app.kubernetes.io/instance: github-actions-runner
    cloud-provider: aws
    platform: eks
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: github-actions-runner
    app.kubernetes.io/instance: github-actions-runner
    app.kubernetes.io/component: controller
