apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-actions-runner
  namespace: github-actions-runner
  labels:
    app.kubernetes.io/name: github-actions-runner
    app.kubernetes.io/instance: github-actions-runner
    cloud-provider: aws
    platform: eks
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::ACCOUNT_ID:role/github-actions-runner-role"
automountServiceAccountToken: true
