apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: keda
  labels:
    app.kubernetes.io/name: keda
    app.kubernetes.io/instance: keda
    cloud-provider: aws
    platform: eks
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: keda
subjects:
  - kind: ServiceAccount
    name: keda
    namespace: keda
