apiVersion: v1
kind: Service
metadata:
  name: keda
  namespace: keda
  labels:
    app.kubernetes.io/name: keda
    app.kubernetes.io/instance: keda
    cloud-provider: aws
    platform: eks
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: keda
    app.kubernetes.io/instance: keda
    app.kubernetes.io/component: controller
