apiVersion: v1
kind: ServiceAccount
metadata:
  name: keda
  namespace: keda
  labels:
    app.kubernetes.io/name: keda
    app.kubernetes.io/instance: keda
    cloud-provider: aws
    platform: eks
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::ACCOUNT_ID:role/keda-role"
automountServiceAccountToken: true
