- op: replace
  path: /spec/replicas
  value: 2
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: ENV
    value: qa
- op: replace
  path: /spec/template/spec/containers/0/resources/limits/cpu
  value: 300m
- op: replace
  path: /spec/template/spec/containers/0/resources/limits/memory
  value: 384Mi
- op: replace
  path: /spec/template/spec/containers/0/resources/requests/cpu
  value: 150m
- op: replace
  path: /spec/template/spec/containers/0/resources/requests/memory
  value: 192Mi

