# OpenSearch Exporter DaemonSet config for EKS nodes

daemonset:
  enabled: true

replicaCount: 1  # ignored when daemonset is enabled

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

service:
  type: ClusterIP
  port: 9108

config:
  opensearch:
    uri: https://your-opensearch-cluster-endpoint:443
    username: os_exporter_user  # created in OpenSearch
    password: os_exporter_pass  # recommended to load from a secret

securityContext:
  runAsUser: 1000
  runAsGroup: 3000
  fsGroup: 2000

tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
  - key: "node-role.kubernetes.io/master"
    operator: "Exists"
    effect: "NoSchedule"

nodeSelector:
  kubernetes.io/os: linux
