apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: payments-stage
resources:
  - ../../base
images:
  - name: gcr.io/mutech2030/rhesis-sdk
    newName: gcr.io/mutech2030/rhesis-sdk
    newTag: 1.0.0-stage
labels:
  - pairs:
      app: rhesis-sdk
      environment: stage
patches:
  - target:
      kind: Deployment
      name: rhesis-sdk
    path: patch-deployment.yaml
