apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: payments


resources:
  - ../../base
  - ../../../../components/calico  
components:
  - ../../../../components/debug

images:
  - name: mutech2030/backend
    newName: mutech2030/backend
    newTag: 1.1.0

labels:
  - pairs:
      app: backend
      environment: dev


patches:
  - target:
      kind: Deployment
      name: backend
    path: patch-deployment.yaml
