apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rhesis-sdk
  labels:
    app.kubernetes.io/name: rhesis-sdk
    app.kubernetes.io/instance: rhesis-sdk
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/component: sdk
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rhesis-sdk
  minReplicas: 2
  maxReplicas: 12
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
