apiVersion: v1
kind: Secret
metadata:
  name: rhesis-sdk-secret
  labels:
    app.kubernetes.io/name: rhesis-sdk
    app.kubernetes.io/instance: rhesis-sdk
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/component: sdk
type: Opaque
stringData:
  SDK_API_KEY: "sdk-service-api-key-for-backend-access"
  SIGNING_KEY: "secure-signing-key-for-sdk-tokens"
  ENCRYPTION_KEY: "secure-encryption-key-for-sensitive-data"
