apiVersion: v1
kind: ServiceAccount
metadata:
  name: rhesis-sdk
  labels:
    app.kubernetes.io/name: rhesis-sdk
    app.kubernetes.io/instance: rhesis-sdk
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/component: sdk
automountServiceAccountToken: true
