apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: go-app
    newName: golang
    newTag: 1.20.7-alpine-dev
    
patches:
  - path: patch.yaml
    target:
      kind: Deployment
  - path: patch.yaml
    target:
      kind: Ingress
