resources:
  - ../../namespaces
  - services/service-a
  - ../../components/argocd
  - ../../components/aws-secrets-csi
#  - ../../components/aws-opensearch-exporter
  - ../../components/nginx-ingress
  - ../../components/externaldns
components:
  - ../../components/debug
