apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../namespaces
  - services/service-a
  - services/rhesis-worker
  - services/rhesis-polyphemus
  - services/rhesis-frontend
  - services/rhesis-sdk
  - ../../components/argocd
  - ../../components/aws-secrets-csi
#  - ../../components/aws-opensearch-exporter
  - ../../components/nginx-ingress
  - ../../components/externaldns
  - ../../components/calico/overlays/dev

components:
  - ../../components/debug

