resources:
  - ../../namespaces
  - services/service-a
  - ../../components/argocd
components:
  - ../../components/debug
  - ../../components/aws-secrets-csi
  - ../../components/aws-opensearch-exporter